import os
from dataclasses import dataclass

@dataclass
class ContentConfig:
    """Configuration for content generation"""
    # Video settings
    target_video_length_hint: float = 30.0  # Target total video length for LLM guidance
    
    # Max duration a single video chunk generated by the model can be
    # (e.g., SVD generates ~2-4 secs effectively, ModelScope similar)
    model_max_video_chunk_duration: float = 3.0 
    
    target_resolution: tuple = (1080, 1920)  # Instagram Reel 9:16
    fps: int = 8
    
    # Scene settings (for LLM guidance)
    min_scenes: int = 2 # Min narration/visual scene pairs from LLM
    max_scenes: int = 5 # Max narration/visual scene pairs from LLM
    # LLM hint for how long each narration part should ideally be
    max_scene_narration_duration_hint: float = 5.0 
    
    # Model settings
    use_svd_flow: bool = True  # Use SDXL -> SVD flow instead of direct T2V
    
    # Output settings
    output_dir: str = "instagram_content"
    
    def __post_init__(self):
        os.makedirs(self.output_dir, exist_ok=True) 